### ISSUE TITLE
which numpy version should i use?

### ISSUE THREAD

**Issue by altctrl00** [mjhydri/BeatNet#13]
I used `numpy==1.20.3` ,but it reported that `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`,I tried to upgrade numpy, but `numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.23.1 which is incompatible.` and reported `ImportError: Numba needs NumPy 1.20 or less`

**Comment by dpe0** [comment]
I have the same issue

**Comment by dpe0** [comment]
```
ackend QtAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "F:\Anaconda\envs\audio38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Anaconda\envs\audio38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\nkshv\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "f:\Stuff\Programming\beat manipulator\aaa.py", line 4, in <module>
    bm.wrapper_beatsample(filename=filename, lib='jump-reward-inference', suffix='jump-reward-inference', audio2=bm.generate_sine(0.1, 1000, 44100), scale=1)  
  File "f:\Stuff\Programming\beat manipulator\BeatManipulator.py", line 493, in wrapper_beatsample
    if beatmap is None: beatmap=analyze_beats(filename, samplerate, audio=audio, lib=lib)
  File "f:\Stuff\Programming\beat manipulator\BeatManipulator.py", line 102, in analyze_beats
    from jump_reward_inference.joint_tracker import joint_inference
  File "F:\Anaconda\envs\audio38\lib\site-packages\jump_reward_inference\joint_tracker.py", line 22, in <module>
    from BeatNet.BeatNet import BeatNet
  File "F:\Anaconda\envs\audio38\lib\site-packages\BeatNet\BeatNet.py", line 8, in <module>
    from madmom.features import DBNDownBeatTrackingProcessor
  File "F:\Anaconda\envs\audio38\lib\site-packages\madmom\__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "F:\Anaconda\envs\audio38\lib\site-packages\madmom\audio\__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "madmom\audio\comb_filters.pyx", line 1, in init madmom.audio.comb_filters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by dpe0** [comment]
> I used `numpy==1.20.3` ,but it reported that `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`,I tried to upgrade numpy, but `numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.23.1 which is incompatible.` and reported `ImportError: Numba needs NumPy 1.20 or less`

okay so in my conda 3.8 env I did
pip uninstall numpy
pip install numpy
pip uninstall numba
pip install numba
pip uninstall scipy
pip install scipy
pip uninstall torch
pip install torch

also i had to find a libsndfile.dll and put it next to my .py

so it seems to work but I am not sure. Instead of outputting an array it opened a weird window with stuff in it

**Comment by altctrl00** [comment]
Ok,thanks,I also curious about how to get the time signature using the given examples,all the output is 2D ndarray

**Comment by roimulia2** [comment]
Hey @stunlocked1 are you available for a paid consultant?

**Comment by stunlocked1** [comment]
> Hey @stunlocked1 are you available for a paid consultant?
uuh I am sanctioned

**Comment by roimulia2** [comment]
What does this means? Haha @stunlocked1
