### ISSUE TITLE
Help install BeatNet

### ISSUE THREAD

**Issue by tuanha2000vn** [mjhydri/BeatNet#22]
Hi guys, I'm trying to install this but can't get it running.

This is the step:

OS: Debian AMD64
Python: 3.8

Step:
1. Create virtualenv with 'virtualenv env'
2. Activate the virtualenv 'source env/bin/activate'
3. Install cython 'pip install cython'
4. Install beatnet 'pip install beatnet' => Success
5. Create test.py 
```
//test.py content
from BeatNet.BeatNet import BeatNet
```
6. Run python test.py and got those error
```
python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from BeatNet.BeatNet import BeatNet
  File "/home/user1/Documents/python/beatnet2/env/lib/python3.8/site-packages/BeatNet/BeatNet.py", line 8, in <module>
    from madmom.features import DBNDownBeatTrackingProcessor
  File "/home/user1/Documents/python/beatnet2/env/lib/python3.8/site-packages/madmom/__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/user1/Documents/python/beatnet2/env/lib/python3.8/site-packages/madmom/audio/__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "madmom/audio/comb_filters.pyx", line 1, in init madmom.audio.comb_filters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
Thank you.

**Comment by tuanha2000vn** [comment]
OK, guys, I figure out how to install BeatNet

These are steps required for installing on Debian AMD64 architecture

## 1. Install portaudio for linux
sudo apt-get install portaudio19-dev

## 2. Create virtuelenv and activate it
pip install virtualenv
virtualenv env
source env/bin/activate

## 3. Install the required dependencies
pip install git+https://people.csail.mit.edu/hubert/git/pyaudio.git
pip install git+https://github.com/CPJKU/madmom.git
pip install git+https://github.com/mjhydri/BeatNet.git

## 4. Create a file and test it
```
from BeatNet.BeatNet import BeatNet

estimator = BeatNet(1, mode='offline', inference_model='DBN', plot=[], thread=False)

Output = estimator.process("/path/to/file.mp3")
print(f'Output {Output}')
```
